[build]
  base = "docs/"
  publish = "build/"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20"

[context.deploy-preview]
  base = "docs/"
  publish = "/"
  command = "yarn run previewBuild"
  
  # adding redirect rule to change the path to /docs
  
  [[redirects]]
    from = "/"
    to = "/docs"