name: Sanity check
on:
  pull_request:
    branches:
      - main

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: Commits Check
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: DCO Check
        uses: tisonkun/actions-dco@v1.1
